### ISSUE TITLE
The test AUC is only 57%?

### ISSUE THREAD

**Issue by Young0222** [shantanu95/exposure-bias-link-rec#1]
According to your code and default settings, I run the experiment on the semi-synthetic data, but the final result is 'roc auc: 0.579746', could you help me?

**Comment by shantanu95** [comment]
Hi, as mentioned in the notebook, the code runs on a very small subset of the real dataset. This is why the AUC even in the notebook is around 57%.  Note that if you have N papers in your citation network, there would be O(N^2) possible pairs of papers, and thus for N papers, the size of the dataset should roughly be O(N^2). Unfortunately, we do not have the same dataset that we used for the paper. The notebook just tests out the neural networks on 32000 pairs (not papers) and only trains for 5 epochs. That is why the AUC is just 57% in the example code. The goal of the notebook is to demonstrate the training pipeline.
